# Generated by Django 4.0.5 on 2022-06-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physical_activities', '0002_remove_exercise_type_alter_exercise_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='physical_activities.exercisetype'),
        ),
    ]
