# Generated by Django 4.0.5 on 2022-07-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_activities', '0004_activity_distance_activity_goal_activity_heart_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
