# Generated by Django 4.0.5 on 2022-07-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0002_defender_goal_minigoal_remove_mesocycle_block_cycles_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicroCycle',
            new_name='TimeCycle',
        ),
        migrations.RemoveField(
            model_name='mesocycle',
            name='defenders',
        ),
        migrations.RemoveField(
            model_name='mesocycle',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='mesocycle',
            name='micro_cycles',
        ),
        migrations.RemoveField(
            model_name='mesocycle',
            name='mini_goals',
        ),
        migrations.DeleteModel(
            name='MacroCycle',
        ),
        migrations.DeleteModel(
            name='MesoCycle',
        ),
    ]
