# Generated by Django 4.0.5 on 2022-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0003_rename_microcycle_timecycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defender',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='minigoal',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='timecycle',
            name='name',
            field=models.CharField(default='Micro Cycle', max_length=50, unique=True),
        ),
    ]
