# Generated by Django 4.0.5 on 2022-07-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodization', '0004_alter_defender_name_alter_goal_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Macro Cycle', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MesoCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Meso Cycle', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Micro Cycle', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='defender',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='minigoal',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='TimeCycle',
        ),
        migrations.AddField(
            model_name='microcycle',
            name='defenders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.defender'),
        ),
        migrations.AddField(
            model_name='microcycle',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.goal'),
        ),
        migrations.AddField(
            model_name='microcycle',
            name='mini_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.minigoal'),
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='defenders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.defender'),
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.goal'),
        ),
        migrations.AddField(
            model_name='mesocycle',
            name='mini_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.minigoal'),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='defenders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.defender'),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.goal'),
        ),
        migrations.AddField(
            model_name='macrocycle',
            name='mini_goals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='periodization.minigoal'),
        ),
    ]
